export type Method = "GET" | "POST" | "PUT";
export type Auth = "public" | "apikey" | "operator" | "admin";

export interface Field {
  name: string;
  type: string;
  required: boolean;
  desc: string;
}

export interface Endpoint {
  id: string;
  group: string;
  method: Method;
  path: string;
  auth: Auth;
  summary: string;
  description?: string;
  headers?: Field[];
  query?: Field[];
  body?: Field[];
  request?: string;
  response: string;
  responseFields?: Field[];
  note?: string;
}

export const BASE_URL = "http://localhost:4000";

export const authNotes: Record<Auth, string> = {
  public: "No credentials required.",
  apikey: "Requires a service API key in the X-API-Key header.",
  operator: "Requires a bearer token from /v1/auth/login (any operator).",
  admin: "Requires a bearer token belonging to an admin.",
};

export const endpoints: Endpoint[] = [
  // ── Decisions ─────────────────────────────────────────────
  {
    id: "decide",
    group: "Decisions",
    method: "POST",
    path: "/v1/decisions",
    auth: "apikey",
    summary: "Score an event and return a verdict",
    description:
      "The one endpoint on the request path. Normalizes the event, scores it against the active policy, and returns allow / challenge / review / deny. Rate-limited per API key (429 with Retry-After after RATE_LIMIT_DECISIONS_PER_MIN, default 600/min); every response carries X-RateLimit-Limit and X-RateLimit-Remaining.",
    headers: [
      { name: "X-API-Key", type: "string", required: true, desc: "A service API key created by an admin in the dashboard." },
      { name: "Idempotency-Key", type: "string", required: false, desc: "Retry-safe: the same key returns the original decision instead of recomputing. Defaults to the event id." },
      { name: "X-Correlation-Id", type: "string", required: false, desc: "Threaded through logs and events for tracing." },
    ],
    body: [
      { name: "type", type: '"card.authorize" | "card.capture" | "card.refund" | "payment.authorize" | "wallet.withdraw" | "account.login" | "order.place"', required: true, desc: "Channel-agnostic event type. Selects which ruleset and policy apply." },
      { name: "amount", type: "number", required: false, desc: "Transaction value, for money-bearing events. Non-negative. Feeds amount rules and the per-user anomaly baseline." },
      { name: "currency", type: "string(3)", required: false, desc: "ISO-4217 code, e.g. USD, ETB. Required when amount is present." },
      { name: "subject.userId", type: "string", required: true, desc: "The acting user's stable id. The primary entity in the graph and the key for anomaly baselines." },
      { name: "subject.deviceId", type: "string", required: false, desc: "Device fingerprint. Powers velocity, first-seen and device-linking (graph) signals." },
      { name: "subject.ip", type: "string", required: false, desc: "Client IP. Linked in the entity graph (shared-IP / ring signals). Never placed in URLs or logs." },
      { name: "subject.phone", type: "string", required: false, desc: "MSISDN (phone number) for mobile-money / telecom rails. A graph entity — flags SIM-box / account-farming via graph.usersOnPhone." },
      { name: "subject.channel", type: "string", required: false, desc: 'Origin rail, e.g. "visa", "telebirr", "web".' },
      { name: "instrument.kind", type: '"card" | "wallet" | "bank"', required: false, desc: "Payment instrument type, for value-bearing events." },
      { name: "instrument.bin", type: "string(6-8)", required: false, desc: "Card issuer BIN — the first 6–8 digits only. Never send a full PAN." },
      { name: "instrument.issuerCountry", type: "string(2)", required: false, desc: "ISO-3166 issuer country, e.g. US." },
      { name: "instrument.threeDS", type: "boolean", required: false, desc: "Whether the transaction carried a 3-D Secure result." },
      { name: "attributes", type: "Record<string, string | number | boolean>", required: false, desc: "Additional validated scalar signals, e.g. { geoMismatch: true }. Readable in rules as attr.<key>." },
    ],
    request: `{
  "type": "card.authorize",
  "amount": 3500, "currency": "USD",
  "subject": { "userId": "usr_3f9a", "deviceId": "dev_2b1", "ip": "203.0.113.7", "channel": "visa" },
  "instrument": { "kind": "card", "bin": "411111", "issuerCountry": "US", "threeDS": false }
}`,
    response: `{
  "id": "vd_0mu4…", "eventId": "evt_0mu4…",
  "verdict": "%review%", "score": 55,
  "reasons": [{ "tag": "takeover", "points": 33 }, { "tag": "no_3ds", "points": 22 }],
  "policyId": "pol_card_authorize", "policyVersion": "v0.4.0",
  "decidedAt": "2026-09-17T10:22:00.000Z"
}`,
    responseFields: [
      { name: "id", type: "string", required: true, desc: "The verdict id (prefixed vd_). Primary key in the append-only verdict log." },
      { name: "eventId", type: "string", required: true, desc: "The id assigned to this event. Use it to correlate a later chargeback label or case." },
      { name: "verdict", type: '"allow" | "challenge" | "review" | "deny"', required: true, desc: "The decision. allow = proceed; challenge = step-up (3DS/OTP); review = opens a case; deny = block." },
      { name: "score", type: "number (0–100)", required: true, desc: "The risk score the policy banded into the verdict. -1 for a list/degraded short-circuit that skipped scoring." },
      { name: "reasons", type: "{ tag: string; points: number }[]", required: true, desc: "Every signal that fired and the points it contributed — the full, attributable explanation." },
      { name: "policyId", type: "string", required: true, desc: "The policy that decided this event." },
      { name: "policyVersion", type: "string", required: true, desc: "The exact policy version applied — pin for audit and replay." },
      { name: "decidedAt", type: "string (ISO-8601)", required: true, desc: "When the verdict was reached." },
    ],
    note: "verdict is one of %allow% · %challenge% · %review% · %deny%. A review verdict opens a case. Send an Idempotency-Key to make retries safe.",
  },

  // ── Auth ──────────────────────────────────────────────────
  {
    id: "auth-status",
    group: "Auth",
    method: "GET",
    path: "/v1/auth/status",
    auth: "public",
    summary: "Whether an admin exists yet",
    response: `{ "needsBootstrap": true }`,
    note: "needsBootstrap is true until the first (admin) account is created.",
  },
  {
    id: "auth-register",
    group: "Auth",
    method: "POST",
    path: "/v1/auth/register",
    auth: "public",
    summary: "Bootstrap the admin account",
    description: "Creates the first user as admin. Once any user exists this returns 403 REGISTRATION_CLOSED — further operators are added by an admin.",
    body: [
      { name: "email", type: "string", required: true, desc: "Login email (normalized lowercase)." },
      { name: "password", type: "string", required: true, desc: "At least 8 characters. Stored scrypt-hashed." },
    ],
    request: `{ "email": "admin@bank.com", "password": "••••••••" }`,
    response: `{ "token": "eyJ…", "user": { "email": "admin@bank.com", "role": "admin" } }`,
  },
  {
    id: "auth-login",
    group: "Auth",
    method: "POST",
    path: "/v1/auth/login",
    auth: "public",
    summary: "Exchange credentials for a token",
    description: "Returns a bearer token valid for 12 hours. Rate-limited per IP (429 with Retry-After after RATE_LIMIT_LOGIN_PER_MIN attempts, default 10/min).",
    body: [
      { name: "email", type: "string", required: true, desc: "Operator login email." },
      { name: "password", type: "string", required: true, desc: "Operator password." },
    ],
    request: `{ "email": "maya@bank.com", "password": "••••••••" }`,
    response: `{ "token": "eyJ…", "user": { "email": "maya@bank.com", "role": "analyst" } }`,
    note: "Send the token as `Authorization: Bearer <token>` on operator endpoints.",
  },
  {
    id: "auth-users-list",
    group: "Auth",
    method: "GET",
    path: "/v1/auth/users",
    auth: "admin",
    summary: "List operators",
    response: `[{ "email": "maya@bank.com", "role": "analyst", "createdAt": "…" }]`,
  },
  {
    id: "auth-users-create",
    group: "Auth",
    method: "POST",
    path: "/v1/auth/users",
    auth: "admin",
    summary: "Add an operator",
    body: [
      { name: "email", type: "string", required: true, desc: "" },
      { name: "password", type: "string", required: true, desc: "Temporary password, ≥ 8 chars." },
      { name: "role", type: '"analyst" | "admin"', required: false, desc: "Defaults to analyst." },
    ],
    request: `{ "email": "ana@bank.com", "password": "••••••••", "role": "analyst" }`,
    response: `{ "email": "ana@bank.com", "role": "analyst", "createdAt": "…" }`,
  },
  {
    id: "auth-logout",
    group: "Auth",
    method: "POST",
    path: "/v1/auth/logout",
    auth: "operator",
    summary: "Log out (revoke this token)",
    description: "Revokes the presented bearer token immediately, before it would expire.",
    response: `{ "ok": true }`,
  },
  {
    id: "auth-logout-all",
    group: "Auth",
    method: "POST",
    path: "/v1/auth/logout-all",
    auth: "operator",
    summary: "Log out everywhere",
    description: "Revokes every active session for the current user — use after a suspected compromise.",
    response: `{ "ok": true }`,
  },
  {
    id: "auth-refresh",
    group: "Auth",
    method: "POST",
    path: "/v1/auth/refresh",
    auth: "operator",
    summary: "Refresh the token",
    description: "Exchanges a still-valid token for a fresh one (sliding session). The old token stays valid until it expires.",
    response: `{ "token": "eyJ…", "user": { "email": "maya@bank.com", "role": "analyst" } }`,
  },

  // ── Cases ─────────────────────────────────────────────────
  {
    id: "list-cases",
    group: "Cases",
    method: "GET",
    path: "/v1/cases",
    auth: "operator",
    summary: "List the review queue",
    query: [{ name: "queue", type: "string", required: false, desc: 'Defaults to "risk-ops".' }],
    response: `[{ "id": "cse_…", "eventId": "evt_…", "verdictId": "vd_…", "queue": "risk-ops",
   "verdict": "%review%", "score": 55, "status": "open",
   "openedAt": "2026-09-17T10:22:00.000Z", "audit": [ … ] }]`,
    responseFields: [
      { name: "id", type: "string", required: true, desc: "Case id (cse_)." },
      { name: "eventId", type: "string", required: true, desc: "The event that opened the case." },
      { name: "verdictId", type: "string", required: true, desc: "The verdict that opened it." },
      { name: "queue", type: "string", required: true, desc: "The review queue the case sits in." },
      { name: "verdict", type: '"review"', required: true, desc: "Always review — only review verdicts open cases." },
      { name: "score", type: "number", required: true, desc: "The risk score at decision time." },
      { name: "status", type: '"open" | "assigned" | "resolved"', required: true, desc: "Case lifecycle state." },
      { name: "assignedTo", type: "string", required: false, desc: "Analyst email, once assigned." },
      { name: "resolution", type: "{ outcome, analyst, note?, at }", required: false, desc: "Present once resolved." },
      { name: "openedAt", type: "string (ISO-8601)", required: true, desc: "When the case opened." },
      { name: "audit", type: "{ action, at, actor, detail? }[]", required: true, desc: "Append-only trail: opened / assigned / resolved, each with actor and timestamp." },
    ],
    note: "Same object shape is returned by GET /v1/cases/:id.",
  },
  {
    id: "get-case",
    group: "Cases",
    method: "GET",
    path: "/v1/cases/:id",
    auth: "operator",
    summary: "Fetch one case with its audit trail",
    response: `{ "id": "cse_…", "status": "assigned", "assignedTo": "maya@bank.com", "audit": [ … ] }`,
    note: "404 when the case does not exist.",
  },
  {
    id: "assign-case",
    group: "Cases",
    method: "POST",
    path: "/v1/cases/:id/assign",
    auth: "operator",
    summary: "Assign a case to yourself",
    response: `{ "id": "cse_…", "status": "assigned", "assignedTo": "maya@bank.com" }`,
    note: "The analyst is taken from your token, not the body.",
  },
  {
    id: "resolve-case",
    group: "Cases",
    method: "POST",
    path: "/v1/cases/:id/resolve",
    auth: "operator",
    summary: "Resolve a case and emit a label",
    body: [
      { name: "outcome", type: '"fraud" | "legit" | "inconclusive"', required: true, desc: 'Ground truth. "inconclusive" records no label.' },
      { name: "note", type: "string", required: false, desc: "Rationale kept on the case." },
    ],
    request: `{ "outcome": "fraud", "note": "confirmed ATO" }`,
    response: `{ "id": "cse_…", "status": "resolved", "resolution": { "outcome": "fraud", … } }`,
    note: "409 if already resolved. Resolving feeds a training label into Feedback.",
  },

  // ── Config ────────────────────────────────────────────────
  {
    id: "cfg-rules",
    group: "Config",
    method: "GET",
    path: "/v1/rules",
    auth: "operator",
    summary: "The active rulesets, rendered as DSL",
    response: `[{ "eventType": "card.authorize", "version": "seed@v0.4",
   "rules": [{ "id": "r_velocity", "tag": "velocity", "weight": 28, "dsl": "rule r_velocity { … }" }] }]`,
  },
  {
    id: "cfg-policies",
    group: "Config",
    method: "GET",
    path: "/v1/policies",
    auth: "operator",
    summary: "The active policies and their bands",
    response: `[{ "eventType": "card.authorize",
   "policy": { "id": "pol_card_authorize", "version": "v0.4.0", "onError": "fail_open",
     "bands": [{ "verdict": "%allow%", "min": 0, "max": 24 }, … ] } }]`,
  },
  {
    id: "cfg-publish",
    group: "Config",
    method: "POST",
    path: "/v1/policies",
    auth: "admin",
    summary: "Publish a new policy version",
    description: "Validated: bands must cover 0–100 with no gaps or overlaps. The new version becomes active immediately; the previous one is retained for rollback.",
    body: [
      { name: "id", type: "string", required: true, desc: "Existing policy id." },
      { name: "version", type: "string", required: true, desc: "New, immutable version label." },
      { name: "onError", type: '"fail_open" | "fail_closed"', required: true, desc: "Fallback verdict on a degraded engine." },
      { name: "bands", type: "Band[]", required: true, desc: "{ verdict, min, max, reviewQueue? } contiguous over 0–100." },
    ],
    request: `{ "id": "pol_card_authorize", "version": "v0.4.1", "onError": "fail_closed",
  "bands": [ { "verdict": "allow", "min": 0, "max": 20 }, … ] }`,
    response: `{ "ok": true, "version": "v0.4.1" }`,
  },
  {
    id: "cfg-rollback",
    group: "Config",
    method: "POST",
    path: "/v1/policies/:id/rollback",
    auth: "admin",
    summary: "Roll a policy back to an earlier version",
    body: [{ name: "toVersion", type: "string", required: true, desc: "A version from the policy's history." }],
    request: `{ "toVersion": "v0.4.0" }`,
    response: `{ "ok": true }`,
  },
  {
    id: "cfg-history",
    group: "Config",
    method: "GET",
    path: "/v1/policies/:id/history",
    auth: "operator",
    summary: "A policy's version history",
    response: `["v0.4.0", "v0.4.1"]`,
  },
  {
    id: "cfg-simulate",
    group: "Config",
    method: "POST",
    path: "/v1/policies/:id/simulate",
    auth: "operator",
    summary: "See which verdict a score would get",
    body: [{ name: "score", type: "number", required: true, desc: "0–100." }],
    request: `{ "score": 61 }`,
    response: `{ "verdict": "%review%", "reviewQueue": "risk-ops" }`,
    note: "Test config changes without sending a real event.",
  },
  {
    id: "cfg-verdicts",
    group: "Config",
    method: "GET",
    path: "/v1/verdicts",
    auth: "operator",
    summary: "Recent entries from the append-only verdict log",
    query: [{ name: "limit", type: "number", required: false, desc: "1–100, default 25." }],
    response: `[{ "id": "vd_…", "verdict": "%deny%", "score": 82, "decidedAt": "…" }]`,
  },
  {
    id: "cfg-backtest",
    group: "Config",
    method: "POST",
    path: "/v1/backtest",
    auth: "admin",
    summary: "Replay a candidate rule/policy change over labeled history",
    description:
      "Re-runs a candidate policy (and optionally a candidate ruleset) against the stored event + feature snapshots for events that have a fraud/legit label, and reports how it would have performed versus the live policy. Read-only — nothing is published.",
    body: [
      { name: "eventType", type: "string", required: true, desc: "Which event type's history to replay, e.g. card.authorize." },
      { name: "policy", type: "object", required: false, desc: "Candidate { bands, onError } to test. Omit to keep the live policy." },
      { name: "rules", type: "Rule[]", required: false, desc: "Candidate ruleset to re-evaluate. Omit to reuse each decision's recorded score." },
    ],
    request: `{
  "eventType": "card.authorize",
  "policy": { "bands": [
    { "verdict": "allow", "min": 0, "max": 34 },
    { "verdict": "review", "min": 35, "max": 69, "reviewQueue": "risk-ops" },
    { "verdict": "deny", "min": 70, "max": 100 }
  ] }
}`,
    response: `{
  "eventType": "card.authorize",
  "sampleSize": 1240, "labeled": 312,
  "candidate": { "truePositives": 190, "falsePositives": 40, "falseNegatives": 22, "trueNegatives": 60, "precision": 0.83, "recall": 0.9, "falsePositiveRate": 0.19 },
  "baseline": { "truePositives": 170, "falsePositives": 55, "falseNegatives": 42, "trueNegatives": 45 },
  "delta": { "fraudCaught": 20, "falsePositives": -15, "flips": 48 }
}`,
    responseFields: [
      { name: "eventType", type: "string", required: true, desc: "The event type replayed." },
      { name: "sampleSize", type: "number", required: true, desc: "Replay samples available for this event type." },
      { name: "labeled", type: "number", required: true, desc: "Of those, how many had a fraud/legit label and were scored. A candidate is only judged on labeled history." },
      { name: "candidate.truePositives", type: "number", required: true, desc: "Labeled-fraud events the candidate would flag (review/challenge/deny)." },
      { name: "candidate.falsePositives", type: "number", required: true, desc: "Labeled-legit events the candidate would flag." },
      { name: "candidate.falseNegatives", type: "number", required: true, desc: "Labeled-fraud events the candidate would allow." },
      { name: "candidate.trueNegatives", type: "number", required: true, desc: "Labeled-legit events the candidate would allow." },
      { name: "candidate.precision", type: "number (0–1)", required: true, desc: "TP ÷ (TP + FP) for the candidate." },
      { name: "candidate.recall", type: "number (0–1)", required: true, desc: "TP ÷ (TP + FN) — share of fraud caught." },
      { name: "candidate.falsePositiveRate", type: "number (0–1)", required: true, desc: "FP ÷ (FP + TN)." },
      { name: "baseline.*", type: "object", required: true, desc: "The same confusion counts for the currently-live policy, on the same labeled set." },
      { name: "delta.fraudCaught", type: "number", required: true, desc: "Candidate TP minus baseline TP. Positive = more fraud caught." },
      { name: "delta.falsePositives", type: "number", required: true, desc: "Candidate FP minus baseline FP. Negative = fewer false positives." },
      { name: "delta.flips", type: "number", required: true, desc: "Decisions whose verdict would change versus what actually happened." },
    ],
    note: "Powers the dashboard's test-before-you-publish panel. 400 if the candidate policy has gaps.",
  },

  // ── API Keys ──────────────────────────────────────────────
  {
    id: "keys-list",
    group: "API Keys",
    method: "GET",
    path: "/v1/apikeys",
    auth: "admin",
    summary: "List service keys",
    response: `[{ "id": "key_…", "name": "payment-gateway", "prefix": "vk_live_a1b2c3",
   "createdBy": "admin@bank.com", "createdAt": "…", "revoked": false }]`,
    note: "Only the prefix is stored for display — the full key is never retrievable.",
  },
  {
    id: "keys-create",
    group: "API Keys",
    method: "POST",
    path: "/v1/apikeys",
    auth: "admin",
    summary: "Create a service key",
    description: "Optionally scope the key to specific actions and set an expiry. A key with no scopes grants both.",
    body: [
      { name: "name", type: "string", required: true, desc: "A label, e.g. the service that will use it." },
      { name: "scopes", type: '("decisions" | "labels")[]', required: false, desc: "Actions the key may perform. Omit for full access (both)." },
      { name: "expiresInDays", type: "number", required: false, desc: "Days until the key expires. Omit for a key that never expires." },
    ],
    request: `{ "name": "payment-gateway", "scopes": ["decisions"], "expiresInDays": 90 }`,
    response: `{ "plaintext": "vk_live_a1b2c3…",   // shown ONCE — store it now
  "key": { "id": "key_…", "name": "payment-gateway", "prefix": "vk_live_a1b2c3",
    "scopes": ["decisions"], "expiresAt": "2026-12-16T…", "expired": false,
    "createdBy": "admin@bank.com", "createdAt": "2026-09-17T10:00:00.000Z", "revoked": false } }`,
    responseFields: [
      { name: "plaintext", type: "string", required: true, desc: "The full key (vk_live_…). Returned only on creation — it is never recoverable afterwards." },
      { name: "key.id", type: "string", required: true, desc: "Key id, used to revoke it." },
      { name: "key.name", type: "string", required: true, desc: "The label you gave it." },
      { name: "key.prefix", type: "string", required: true, desc: "First chars of the key, shown in listings for identification." },
      { name: "key.scopes", type: "string[]", required: true, desc: "Actions this key may perform." },
      { name: "key.expiresAt", type: "string (ISO-8601)", required: false, desc: "When the key expires, if ever." },
      { name: "key.expired", type: "boolean", required: true, desc: "Whether the key has already expired." },
      { name: "key.revoked", type: "boolean", required: true, desc: "Whether the key has been revoked." },
    ],
    note: "Send the plaintext as X-API-Key. A request to an endpoint outside the key's scope is rejected with 403. Only the SHA-256 hash is stored.",
  },
  {
    id: "keys-revoke",
    group: "API Keys",
    method: "POST",
    path: "/v1/apikeys/:id/revoke",
    auth: "admin",
    summary: "Revoke a key immediately",
    response: `{ "ok": true }`,
  },

  // ── Analytics ─────────────────────────────────────────────
  {
    id: "analytics",
    group: "Analytics",
    method: "GET",
    path: "/v1/analytics/summary",
    auth: "operator",
    summary: "Rollups from the verdict log and resolved cases",
    description: "A read-model maintained by a projector that consumes verdict + case events — never queried off the write path.",
    response: `{
  "totals": { "decisions": 1240, "byVerdict": { "allow": 900, "review": 210, "deny": 130 } },
  "scoreBuckets": [ … 11 buckets 0–100 … ],
  "topTags": { "velocity": 320, "takeover": 180 },
  "byDay": { "2026-09-17": { "total": 210, "review": 40, "deny": 22 } },
  "cases": { "resolved": 90, "fraud": 61, "legit": 29 },
  "labels": { "fraud": 74, "legit": 29, "analyst": 90, "chargeback": 13 },
  "falsePositiveRate": 0.32
}`,
    responseFields: [
      { name: "totals.decisions", type: "number", required: true, desc: "All decisions seen by the projector." },
      { name: "totals.byVerdict", type: "Record<verdict, number>", required: true, desc: "Count per verdict (allow/challenge/review/deny)." },
      { name: "scoreBuckets", type: "number[11]", required: true, desc: "Score histogram in 10-point buckets (0–9 … 100)." },
      { name: "topTags", type: "Record<tag, number>", required: true, desc: "How often each signal fired." },
      { name: "byDay", type: "Record<date, DayCounts>", required: true, desc: "Per-day totals and verdict breakdown." },
      { name: "cases", type: "{ resolved, fraud, legit, inconclusive }", required: true, desc: "Analyst case-resolution outcomes." },
      { name: "labels", type: "{ fraud, legit, analyst, chargeback }", required: true, desc: "Ground-truth labels by outcome and source — includes chargebacks that never became cases." },
      { name: "falsePositiveRate", type: "number (0–1)", required: true, desc: "legit ÷ (fraud + legit) over resolved cases." },
    ],
  },
  {
    id: "model",
    group: "Analytics",
    method: "GET",
    path: "/v1/model",
    auth: "operator",
    summary: "The adaptive model's learned signal weights",
    description:
      "Per-tag weights the adaptive scorer learns from labels — how often each signal rode a fraud outcome. Projected even when the weighted scorer is live, so you can see what the learned model would do before switching SCORER=learned.",
    response: `{
  "active": "weighted",
  "weights": [
    { "tag": "takeover", "fraud": 41, "legit": 3, "weight": 42, "trusted": true },
    { "tag": "velocity", "fraud": 22, "legit": 9, "weight": 32, "trusted": true }
  ]
}`,
    responseFields: [
      { name: "active", type: '"weighted" | "learned"', required: true, desc: "Which scorer is live (set by the SCORER env var). The model is projected either way." },
      { name: "weights[].tag", type: "string", required: true, desc: "The signal tag." },
      { name: "weights[].fraud", type: "number", required: true, desc: "Times this tag rode a fraud label." },
      { name: "weights[].legit", type: "number", required: true, desc: "Times this tag rode a legit label." },
      { name: "weights[].weight", type: "number (0–45)", required: true, desc: "Learned points, from the smoothed fraud rate. Used by the learned scorer." },
      { name: "weights[].trusted", type: "boolean", required: true, desc: "Whether it has enough labels (≥3) to be used; until then the scorer keeps the hand weight." },
    ],
  },
  {
    id: "graph-neighborhood",
    group: "Graph",
    method: "GET",
    path: "/v1/graph/:kind/:id",
    auth: "operator",
    summary: "An entity's linked users, devices, IPs and phones, and its cluster size",
    description:
      "The entity graph links the identifiers events carry (kind is user, device, ip or phone). ringSize is the connected cluster the entity sits in — the ring signal rules read as graph.ringSize; a shared phone drives graph.usersOnPhone (SIM-box / mobile-money farming). Cards are not nodes: only the issuer BIN is held, which would over-link.",
    response: `{
  "kind": "device", "id": "dev_ring",
  "users": ["usr_1", "usr_2", "usr_3"],
  "devices": [], "ips": ["203.0.113.7"],
  "ringSize": 8
}`,
    responseFields: [
      { name: "kind", type: '"user" | "device" | "ip"', required: true, desc: "The entity kind queried (from the path)." },
      { name: "id", type: "string", required: true, desc: "The entity id queried." },
      { name: "users", type: "string[]", required: true, desc: "Distinct users directly linked to this entity." },
      { name: "devices", type: "string[]", required: true, desc: "Distinct devices directly linked." },
      { name: "ips", type: "string[]", required: true, desc: "Distinct IPs directly linked." },
      { name: "ringSize", type: "number", required: true, desc: "Size of the connected cluster this entity sits in (walk capped at 500). 1 means unconnected." },
    ],
    note: "404-safe: an unknown entity returns empty links and ringSize 1.",
  },

  // ── Webhooks ──────────────────────────────────────────────
  {
    id: "webhooks-list",
    group: "Webhooks",
    method: "GET",
    path: "/v1/webhooks",
    auth: "admin",
    summary: "List webhook endpoints and their delivery status",
    response: `{
  "events": ["verdict.reached.v1", "case.resolved.v1", "label.recorded.v1"],
  "endpoints": [{ "id": "whk_…", "url": "https://app/hooks", "events": ["verdict.reached.v1"],
    "active": true, "lastStatus": "delivered", "failures": 0 }]
}`,
    responseFields: [
      { name: "events", type: "string[]", required: true, desc: "The events an endpoint may subscribe to." },
      { name: "endpoints[].id", type: "string", required: true, desc: "Endpoint id (used to revoke)." },
      { name: "endpoints[].url", type: "string", required: true, desc: "Where deliveries are POSTed." },
      { name: "endpoints[].events", type: "string[]", required: true, desc: "Subscribed events." },
      { name: "endpoints[].active", type: "boolean", required: true, desc: "Whether it's live." },
      { name: "endpoints[].lastStatus", type: '"delivered" | "failed"', required: false, desc: "Last delivery outcome." },
      { name: "endpoints[].failures", type: "number", required: true, desc: "Consecutive failed deliveries." },
    ],
  },
  {
    id: "webhooks-create",
    group: "Webhooks",
    method: "POST",
    path: "/v1/webhooks",
    auth: "admin",
    summary: "Register an endpoint to receive signed events",
    description:
      "Each delivery is a POST with headers X-Verdict-Event, X-Verdict-Delivery and X-Verdict-Signature (`sha256=<hmac>` of the raw body with the endpoint secret). Verify the signature before trusting the payload. Deliveries are durable: each is retried with exponential backoff and dead-lettered after 8 failed attempts (inspect and re-drive via the delivery-log endpoints).",
    body: [
      { name: "url", type: "string", required: true, desc: "http(s) URL to deliver to." },
      { name: "events", type: "string[]", required: true, desc: "One or more of verdict.reached.v1, case.resolved.v1, label.recorded.v1." },
    ],
    request: `{ "url": "https://app/hooks/verdict", "events": ["verdict.reached.v1"] }`,
    response: `{ "id": "whk_…", "url": "https://app/hooks/verdict", "events": ["verdict.reached.v1"],
  "active": true, "failures": 0, "secret": "whsec_…" }`,
    responseFields: [
      { name: "secret", type: "string", required: true, desc: "The signing secret — returned only on creation. Store it to verify signatures." },
      { name: "id", type: "string", required: true, desc: "Endpoint id." },
    ],
    note: "Delivered payload shape: { id, type, occurredAt, correlationId, data }, where data is the event payload.",
  },
  {
    id: "webhooks-revoke",
    group: "Webhooks",
    method: "POST",
    path: "/v1/webhooks/:id/revoke",
    auth: "admin",
    summary: "Deactivate an endpoint",
    response: `{ "ok": true }`,
  },
  {
    id: "webhooks-deliveries",
    group: "Webhooks",
    method: "GET",
    path: "/v1/webhooks/deliveries",
    auth: "admin",
    summary: "Delivery log (pending & dead-lettered)",
    description: "Deliveries awaiting a retry, and ones that exhausted their attempts (dead-lettered).",
    response: `{ "pending": [{ "id": "whd_…", "endpointId": "whk_…", "event": "verdict.reached.v1",
    "status": "pending", "attempts": 2, "nextAttemptAt": "…", "lastError": "fetch failed" }],
  "dead": [] }`,
  },
  {
    id: "webhooks-redrive",
    group: "Webhooks",
    method: "POST",
    path: "/v1/webhooks/deliveries/redrive",
    auth: "admin",
    summary: "Re-drive dead-lettered deliveries",
    description: "Moves every dead-lettered delivery back to pending for another attempt.",
    response: `{ "requeued": 3 }`,
  },

  // ── Notifications ─────────────────────────────────────────
  {
    id: "notifications-list",
    group: "Notifications",
    method: "GET",
    path: "/v1/notifications",
    auth: "admin",
    summary: "List alert channels and subscribable events",
    response: `{ "events": ["verdict.reached.v1", "case.resolved.v1", "label.recorded.v1", "alert.dead_letter.v1"],
  "channels": [{ "id": "ntf_…", "type": "slack", "urlHint": "https://hooks.slack.com/…",
    "events": ["verdict.reached.v1"], "minVerdict": "deny", "active": true, "failures": 0 }] }`,
  },
  {
    id: "notifications-create",
    group: "Notifications",
    method: "POST",
    path: "/v1/notifications",
    auth: "admin",
    summary: "Add a Slack, Telegram or webhook alert channel",
    description:
      "Slack incoming-webhooks, Telegram bots, and generic HTTPS endpoints. For Telegram, set url to https://api.telegram.org/bot<token>/sendMessage and target to the chat id. For verdict.reached, set minVerdict to only alert at or above a severity (allow < challenge < review < deny). Set throttlePerMin to cap alerts per channel per minute (excess is dropped). Delivery is durable — queued, retried with backoff, and dead-lettered — and runs off the decision path.",
    body: [
      { name: "type", type: '"slack" | "telegram" | "webhook"', required: true, desc: "Channel kind." },
      { name: "url", type: "string", required: true, desc: "HTTPS URL (Slack webhook, Telegram bot sendMessage URL, or your endpoint). Stored server-side; shown masked." },
      { name: "target", type: "string", required: false, desc: "Telegram chat id — required for the telegram type." },
      { name: "events", type: "string[]", required: true, desc: "Events to alert on (see the list endpoint)." },
      { name: "minVerdict", type: '"allow" | "challenge" | "review" | "deny"', required: false, desc: "verdict.reached severity floor." },
      { name: "throttlePerMin", type: "number", required: false, desc: "Max alerts per minute for this channel (0 = unlimited); omit for the env default." },
    ],
    request: `{ "type": "telegram", "url": "https://api.telegram.org/bot<token>/sendMessage", "target": "-1001234567890", "events": ["verdict.reached.v1"], "minVerdict": "deny", "throttlePerMin": 30 }`,
    response: `{ "id": "ntf_…", "type": "slack", "urlHint": "https://hooks.slack.com/…", "events": ["verdict.reached.v1"], "minVerdict": "deny", "throttlePerMin": 30, "active": true, "failures": 0 }`,
  },
  {
    id: "notifications-test",
    group: "Notifications",
    method: "POST",
    path: "/v1/notifications/:id/test",
    auth: "admin",
    summary: "Send a test alert to a channel",
    response: `{ "ok": true }`,
  },
  {
    id: "notifications-revoke",
    group: "Notifications",
    method: "POST",
    path: "/v1/notifications/:id/revoke",
    auth: "admin",
    summary: "Deactivate a channel",
    response: `{ "ok": true }`,
  },
  {
    id: "notifications-deliveries",
    group: "Notifications",
    method: "GET",
    path: "/v1/notifications/deliveries",
    auth: "admin",
    summary: "List alert deliveries (pending + dead-lettered)",
    description: "Durable alert deliveries awaiting a retry, and those that exhausted their retries. Bodies are omitted.",
    response: `{ "pending": [{ "id": "ntd_…", "channelId": "ntf_…", "event": "alert.anomaly.v1", "status": "pending", "attempts": 2, "nextAttemptAt": "2026-01-01T00:00:04.000Z", "createdAt": "2026-01-01T00:00:00.000Z" }],
  "dead": [] }`,
  },
  {
    id: "notifications-redrive",
    group: "Notifications",
    method: "POST",
    path: "/v1/notifications/deliveries/redrive",
    auth: "admin",
    summary: "Re-drive dead-lettered alerts",
    description: "Moves every dead-lettered alert delivery back to the queue for another attempt.",
    response: `{ "requeued": 3 }`,
  },

  // ── Settings ──────────────────────────────────────────────
  {
    id: "config-rate-limits-get",
    group: "Settings",
    method: "GET",
    path: "/v1/config/rate-limits",
    auth: "admin",
    summary: "Get rate-limit settings",
    description: "The effective per-minute budgets and whether each is a dashboard override or the env default.",
    response: `{ "windowMs": 60000, "decisionsPerMin": 600, "loginPerMin": 10,
  "overridden": { "decisionsPerMin": false, "loginPerMin": false } }`,
  },
  {
    id: "config-rate-limits-put",
    group: "Settings",
    method: "PUT",
    path: "/v1/config/rate-limits",
    auth: "admin",
    summary: "Update rate-limit settings",
    description: "Override the per-minute budgets at runtime — no redeploy. Send a field as null to revert it to the env default; changes apply within ~10s across replicas.",
    body: [
      { name: "decisionsPerMin", type: "number | null", required: false, desc: "Per-API-key budget for POST /v1/decisions (null = revert to default)." },
      { name: "loginPerMin", type: "number | null", required: false, desc: "Per-IP budget for POST /v1/auth/login (null = revert to default)." },
    ],
    request: `{ "decisionsPerMin": 1200, "loginPerMin": 10 }`,
    response: `{ "windowMs": 60000, "decisionsPerMin": 1200, "loginPerMin": 10,
  "overridden": { "decisionsPerMin": true, "loginPerMin": false } }`,
  },
  {
    id: "config-alerts-get",
    group: "Settings",
    method: "GET",
    path: "/v1/config/alerts",
    auth: "admin",
    summary: "Get alert settings",
    description: "The anomaly z-score threshold at or above which a decision emits alert.anomaly.v1.",
    response: `{ "anomalyZScore": 3, "overridden": { "anomalyZScore": false } }`,
  },
  {
    id: "config-alerts-put",
    group: "Settings",
    method: "PUT",
    path: "/v1/config/alerts",
    auth: "admin",
    summary: "Update alert settings",
    description: "Set the anomaly z-score threshold (send null to revert to the default of 3). Applies within ~10s.",
    body: [{ name: "anomalyZScore", type: "number | null", required: false, desc: "σ above the user's baseline that triggers an anomaly alert (null = default 3)." }],
    request: `{ "anomalyZScore": 2.5 }`,
    response: `{ "anomalyZScore": 2.5, "overridden": { "anomalyZScore": true } }`,
  },
  {
    id: "config-retention-get",
    group: "Settings",
    method: "GET",
    path: "/v1/config/retention",
    auth: "admin",
    summary: "Get retention settings",
    description: "The retention window (in days) for each append-only collection, and whether each is a dashboard override or the env default. 0 means keep forever.",
    response: `{ "sweepMinutes": 60,
  "days": { "verdicts": 365, "activity": 90, "replay": 90, "idempotency": 7, "deadLetter": 30 },
  "overridden": { "verdicts": false, "activity": false, "replay": false, "idempotency": false, "deadLetter": false } }`,
  },
  {
    id: "config-retention-put",
    group: "Settings",
    method: "PUT",
    path: "/v1/config/retention",
    auth: "admin",
    summary: "Update retention settings",
    description: "Set the retention window (days) per collection. 0 keeps that collection forever; send a field as null to revert it to the env default. Applies on the next sweep.",
    body: [
      { name: "verdicts", type: "number | null", required: false, desc: "Days to keep the verdict log (0 = forever, null = env default)." },
      { name: "activity", type: "number | null", required: false, desc: "Days to keep the API activity log." },
      { name: "replay", type: "number | null", required: false, desc: "Days to keep replay samples." },
      { name: "idempotency", type: "number | null", required: false, desc: "Days to keep idempotency keys." },
      { name: "deadLetter", type: "number | null", required: false, desc: "Days to keep dead-lettered outbox rows." },
    ],
    request: `{ "activity": 120, "idempotency": 3 }`,
    response: `{ "sweepMinutes": 60,
  "days": { "verdicts": 365, "activity": 120, "replay": 90, "idempotency": 3, "deadLetter": 30 },
  "overridden": { "verdicts": false, "activity": true, "replay": false, "idempotency": true, "deadLetter": false } }`,
  },
  {
    id: "config-retention-run",
    group: "Settings",
    method: "POST",
    path: "/v1/config/retention/run",
    auth: "admin",
    summary: "Run the retention prune now",
    description: "Trigger a retention sweep immediately (the job also runs on a timer) and return how many records were pruned per collection.",
    response: `{ "ranAt": "2026-01-01T00:00:00.000Z",
  "pruned": { "verdicts": 0, "activity": 4, "replay": 4, "idempotency": 120, "deadLetter": 0 } }`,
  },

  // ── Labels & System ───────────────────────────────────────
  {
    id: "chargeback",
    group: "Labels",
    method: "POST",
    path: "/v1/labels/chargeback",
    auth: "apikey",
    summary: "Record a chargeback as a fraud label",
    description: "A PSP/system endpoint — takes a service API key.",
    headers: [{ name: "X-API-Key", type: "string", required: true, desc: "Service API key." }],
    body: [{ name: "eventId", type: "string", required: true, desc: "The original event that was charged back." }],
    request: `{ "eventId": "evt_…" }`,
    response: `{ "recorded": true }`,
    responseFields: [{ name: "recorded", type: "true", required: true, desc: "Acknowledged; the label is stored and broadcast to scoring and analytics." }],
    note: "202 Accepted. If the event was seen before, its fired tags are credited to the model.",
  },
  {
    id: "privacy-erase",
    group: "Data governance",
    method: "POST",
    path: "/v1/privacy/erase",
    auth: "admin",
    summary: "Erase a user's personal data (right to erasure)",
    description:
      "Removes a user's graph identity, learned spending baseline, and stored replay samples (which hold whole events). The append-only verdict log is out of scope by design — it holds only an event id, verdict and tags — and is governed by a retention window.",
    body: [{ name: "userId", type: "string", required: true, desc: "The user to erase across the engine's stores." }],
    request: `{ "userId": "usr_3f9a" }`,
    response: `{ "userId": "usr_3f9a", "replaySamplesRemoved": 12, "activityEntriesRemoved": 12,
  "graph": true, "baseline": true }`,
    responseFields: [
      { name: "userId", type: "string", required: true, desc: "The user erased." },
      { name: "replaySamplesRemoved", type: "number", required: true, desc: "Replay-log entries deleted for this user." },
      { name: "activityEntriesRemoved", type: "number", required: true, desc: "API activity-log entries deleted for this user." },
      { name: "graph", type: "boolean", required: true, desc: "Whether the graph identity was unlinked and removed." },
      { name: "baseline", type: "boolean", required: true, desc: "Whether the anomaly baseline was dropped." },
    ],
  },
  {
    id: "health",
    group: "System",
    method: "GET",
    path: "/health",
    auth: "public",
    summary: "Liveness probe",
    response: `{ "status": "ok", "name": "verdict-engine", "version": "0.7.0" }`,
  },
  {
    id: "metrics",
    group: "System",
    method: "GET",
    path: "/metrics",
    auth: "public",
    summary: "Prometheus metrics",
    description: "Operational metrics in Prometheus text format — decision latency & outcomes, 429s, degraded decisions, and outbox/webhook delivery counters and queue depth. Keep this on the private port.",
    response: `# HELP verdict_decisions_total Decisions returned, by verdict\n# TYPE verdict_decisions_total counter\nverdict_decisions_total{verdict="allow",cached="false"} 128`,
  },
];
