/** The docs page's sections, as [anchor id, title]. Shared by the docs sidebar and the search index. */
export const DOC_SECTIONS: [string, string][] = [
  ["intro", "Introduction"],
  ["quickstart", "Quickstart"],
  ["integrate", "Integration"],
  ["sdks", "SDKs"],
  ["bestpractices", "Best practices"],
  ["usecases", "Use cases"],
  ["mcp", "LLM & MCP"],
  ["events", "Events & fields"],
  ["signals", "Signals & rules"],
  ["verdicts", "Verdicts & scoring"],
  ["reason-codes", "Reason codes"],
  ["configure", "Configuration"],
  ["dashboard", "Dashboard"],
  ["operate", "Operating"],
  ["intelligence", "Intelligence"],
  ["governance", "Data governance"],
  ["deploy", "Deployment"],
  ["capacity", "Requirements & capacity"],
  ["security", "Security"],
];
