/**
 * The docs search corpus: real passages from the documentation, each tied to the section anchor it
 * lives under. The search engine (lib/search.ts) matches a query against these sentences — not just
 * section titles — and expands the query with the synonym map below so a search phrased in the user's
 * own words ("stop fraud rings", "how fast is it", "who changed a setting") still finds the right
 * passage. Keep bodies to the actual wording used on the page so the matched snippet reads naturally.
 */
export interface Passage {
  /** Anchor id of the /docs section this passage lives under. */
  readonly section: string;
  readonly title: string;
  readonly body: string;
  /** Extra query terms / concepts that should match this passage but may not appear verbatim. */
  readonly terms?: string;
}

export const DOC_PASSAGES: Passage[] = [
  { section: "intro", title: "What Verdict is", body: "An open-source fraud and risk decisioning engine. You send it an event; it returns a verdict — allow, challenge, review, or deny — in a single synchronous call, with a 0–100 score and the exact reasons behind it. It is a decisioning layer, not a data vendor.", terms: "overview what is it risk scoring engine self-hosted open source" },
  { section: "quickstart", title: "Quickstart", body: "One docker compose command brings up Postgres, the engine, and the dashboard. The first person to register becomes the admin, then public sign-up closes. Create a service API key under Keys — shown once, stored only as a SHA-256 hash.", terms: "getting started install setup run bootstrap first steps compose docker" },
  { section: "integrate", title: "Calling the decision API", body: "Right before the irreversible action — authorize a charge, complete a login, release a payout — send the event to POST /v1/decisions and wait for the verdict. Send every identifier you have; absent fields simply mean the rules that read them don't fire.", terms: "integrate how to call endpoint request critical path" },
  { section: "integrate", title: "Batch and async decisions", body: "Backfilling or scoring in bulk? Use POST /v1/decisions/batch for up to 100 events at once, or POST /v1/decisions/async to keep it off your response path — it returns 202 with an id you poll at GET /v1/decisions/{id} or receive by webhook.", terms: "bulk many events background offline queue high volume batch asynchronous" },
  { section: "integrate", title: "Idempotency and retries", body: "Pass an Idempotency-Key — a natural id like the order id — so a retry returns the same verdict instead of scoring twice. Without one it defaults to the event id. This makes a network retry always safe.", terms: "duplicate retry safe exactly once idempotent replay same decision" },
  { section: "sdks", title: "Official client SDKs", body: "Official client libraries wrap the API-key data plane — decide, decideBatch, decideAsync, getDecision and recordChargeback — with typed events and verdicts, a per-request timeout, and automatic retry with backoff on 429, 5xx and network errors. TypeScript and Dart/Flutter are available; Python and React Native are planned.", terms: "sdk client library typescript javascript node dart flutter python react native official wrapper package npm pub install" },
  { section: "sdks", title: "Using an SDK safely", body: "The SDKs are dependency-light and use each platform's native HTTP. They cover the integrator endpoints only; operator and admin actions stay in the dashboard. Keep service keys server-side — a key shipped in a mobile or browser binary can be extracted, so score from a trusted backend or proxy through your server.", terms: "sdk mobile flutter browser key security backend proxy client side install import" },
  { section: "verdicts", title: "Verdicts and scoring", body: "Scoring sums the weights of every matched rule into a 0–100 number, and a policy maps score bands to allow, challenge, review, or deny. Every verdict carries the score and the reasons that produced it, so a decision is always auditable and explainable.", terms: "score bands explainable reasons attributable decision output" },
  { section: "verdicts", title: "Trained ML scorer", body: "Set SCORER=ml for a trained logistic-regression model over the whole feature vector — velocity, device fingerprint, geolocation, graph and anomaly signals — returning a calibrated risk with the per-feature terms as the reasons. Trained offline on a synthetic dataset; inference is a dot-product plus a sigmoid, so it adds nothing to decision latency.", terms: "machine learning model prediction logistic regression AI neural gradient descent train synthetic data accuracy AUC" },
  { section: "verdicts", title: "Hot-swappable cloud model", body: "The ML weights are hot-swappable: point MODEL_URL at a cloud bucket and a retrained model loads and refreshes from there — validated against the feature vector, with the bundled weights as a safe fallback — so you roll out a new model without a redeploy.", terms: "cloud model MODEL_URL remote weights hot swap update model registry bucket S3 refresh flexibility deploy new model" },
  { section: "verdicts", title: "Scaling the ML pipeline", body: "Serving and training scale independently. Serving is a fixed-cost dot-product held in the image — no model server, no GPU — so it adds microseconds and scales horizontally with engine replicas. Training is fully decoupled: the engine only consumes a validated JSON weights file, so you can train on real labels at any scale in an external batch job and publish the weights to S3.", terms: "scalability scale ml pipeline training serving throughput model server gpu batch job retrain offline decoupled performance real labels feature store gbm" },
  { section: "verdicts", title: "Adaptive learned scorer", body: "Set SCORER=learned and the scorer weights each signal by how often it has ridden a fraud label in your own resolved cases and chargebacks. A tag keeps its hand weight until it has enough labels to trust, so a fresh deploy behaves like the weighted scorer and drifts toward your data.", terms: "learning learned adaptive model labels chargeback improve over time train from data" },
  { section: "reason-codes", title: "Reason codes — three layers of why", body: "Every verdict carries three layers, each for a different audience: reasons (the rule tags and points, for analysts), reasonCodes (stable, documented codes like ACCOUNT_TAKEOVER, VELOCITY_HIGH, NETWORK_RING for your ops and dispute team), and customerMessage (one vague line safe to show the cardholder, which never names a signal). So a decline explains itself without teaching a fraudster which rule fired.", terms: "reason code reason-codes error code decline code response code why was it blocked declined dispute team customer message merchant mapping chargeback explain to customer three layers reasonCodes" },
  { section: "reason-codes", title: "Reason code catalog", body: "The full catalog of reason codes the engine can return — VELOCITY_HIGH, ACCOUNT_TAKEOVER, AUTH_WEAK, DEVICE_NEW, DEVICE_SHARED, NETWORK_SHARED_IP, NETWORK_RING, NETWORK_SIM, AMOUNT_HIGH, AMOUNT_ANOMALY, ANOMALY, BLOCKLISTED, WATCHLISTED, SYSTEM_DEGRADED — each with its category and meaning. The codes are a stable published contract you can log, alert on, and map; a custom rule with no mapping returns RISK_OTHER.", terms: "list of reason codes catalog all codes enum error codes decline codes reference table meaning category stable contract map alert takeover velocity network ring blocklist watchlist amount anomaly risk_other" },
  { section: "signals", title: "Geolocation and impossible travel", body: "The client IP is resolved to a coarse location. From the user's previous location the engine derives geo.distanceKm, geo.countryChanged, and geo.impossibleTravel — a move faster than a jet that the same person can't have made. Swap the offline resolver for a GeoIP database in production.", terms: "geo geolocation location ip country distance impossible travel velocity of travel geoip maxmind where is the user" },
  { section: "signals", title: "Device fingerprinting", body: "An optional subject.fingerprint hash yields device.usersOnFingerprint, device.fingerprintFirstSeen, and device.fingerprintDeviceMismatch — the same fingerprint seen on a different deviceId, a cloning or spoofing signal — independent of the client-supplied device id.", terms: "device fingerprint fingerprinting spoofing cloning emulator bot shared device browser" },
  { section: "signals", title: "Entity graph and fraud rings", body: "Users, devices and IPs are linked as they co-occur. Rules read graph.ringSize and link counts (usersOnDevice, usersOnIp, usersOnPhone) to flag rings a single event can't reveal — many accounts on one phone flags a SIM box. Explore any entity's cluster in the Graph tab.", terms: "graph ring cluster network linked accounts fraud ring collusion sim box shared ip account farming" },
  { section: "signals", title: "Anomaly detection", body: "The engine keeps a per-user spending baseline and exposes anomaly.amountZScore — how many standard deviations a charge sits from that user's own history — so a rule can flag 'this doesn't look like this account' without a fixed threshold.", terms: "anomaly outlier zscore unusual spending baseline deviation abnormal" },
  { section: "signals", title: "Velocity signals", body: "Rolling counters from the feature store: velocity.attemptsLast2m, velocity.attemptsLast24h, and velocity.amountLast1h catch bursts of activity from one user.", terms: "velocity rate frequency bursts too many attempts speed of requests" },
  { section: "signals", title: "Rules DSL", body: "A rule proposes: when its condition matches it adds weight under a tag — it never decides on its own. Rules are authored in a small DSL, versioned in git, hot-reloaded, and diffable in review. Rules propose, scoring weighs, policy decides.", terms: "rules dsl conditions author write rule tag weight when then" },
  { section: "configure", title: "Policies and on_error", body: "A policy maps score bands to verdicts with an on_error mode (fail-open or fail-closed) that decides the outcome when a dependency is degraded — on purpose, never silently. Bands must cover 0–100 with no gaps; every version is retained so you can roll back in one click.", terms: "policy bands fail open fail closed on error version rollback thresholds configure" },
  { section: "intelligence", title: "Backtesting a change", body: "Before you ship a rule or policy change, replay it against your labeled history and see how it would have performed — precision, recall, and the deltas in fraud caught, false positives, and verdict flips versus the live policy. It is read-only; nothing is published.", terms: "backtest simulate replay test change precision recall what if before publish shadow" },
  { section: "dashboard", title: "The operator dashboard (admin CMS)", body: "A self-hosted operator console (a separate Next.js app talking to the engine API): analysts work the review queue and resolve cases; admins configure rules, policies, scoring, retention, keys and webhooks, and watch analytics — all server-side. Includes the scoring-model panel, storage & server-disk-health, and the analytics read-model. See the screenshots.", terms: "dashboard admin cms operator console ui screenshots review queue configure analytics scoring model storage disk health screenshot gallery interface panel" },
  { section: "operate", title: "Cases and review queue", body: "A review verdict opens a case in the dashboard queue. An analyst assigns it, works it, and resolves it as fraud, legit, or inconclusive. The analyst is always taken from the authenticated token, never the request body.", terms: "case review queue analyst manual investigate resolve human in the loop" },
  { section: "operate", title: "Config-change audit log", body: "Every operator mutation — a rate-limit or retention tweak, a published policy, a new alert channel or API key — is written to a config-change audit log at GET /v1/audit with the actor, the action, the time and the result; secret-ish fields are redacted. So 'who changed this, and when?' always has an answer.", terms: "audit log who changed history accountability compliance change tracking operator actions" },
  { section: "operate", title: "Webhooks", body: "Webhooks push engine events to your systems in real time. Register an endpoint for verdict.reached, case.resolved or label.recorded; each delivery is a signed POST — verify the X-Verdict-Signature (HMAC-SHA256) before trusting it. Deliveries are durable: retried with backoff and dead-lettered after repeated failure, off the decision path.", terms: "webhook callback push event subscribe signature hmac durable delivery retry dead letter integrate systems" },
  { section: "operate", title: "Alert notifications and throttling", body: "Send events to a person via a Slack incoming-webhook, a Telegram bot, or a generic HTTPS channel. Delivery is durable — queued, retried with backoff and dead-lettered — and throttled per channel (throttlePerMin) so an alert storm can't bury an operator or rate-limit your Slack. Built-in alert.anomaly and alert.dead_letter events reach you too.", terms: "notifications alerts slack telegram ping notify throttle rate limit alert storm channel" },
  { section: "capacity", title: "Performance and throughput", body: "A single engine replica sustained about 300 decisions per second in our benchmark; latency was about 20 ms for a lone request and p50 ~70 ms, p99 ~140 ms under moderate concurrency. Throughput is bound by database latency, not CPU, because each decision makes several round-trips.", terms: "performance speed fast throughput latency benchmark how fast requests per second scale slow p99" },
  { section: "capacity", title: "Retention and pruning", body: "A built-in job deletes rows older than each collection's window — verdict log, activity log, replay samples, idempotency keys and dead-lettered events. Defaults are 365 / 90 / 90 / 7 / 30 days; a window of 0 keeps a collection forever. Tune per deployment via RETENTION_* env vars or at runtime.", terms: "retention prune delete old data age out expire cleanup window how long kept grow unbounded" },
  { section: "capacity", title: "Disk management and storage", body: "GET /v1/config/storage reports the store's size on disk and per-collection row counts, also sampled into the verdict_storage_* metrics each sweep — so you can see what's growing. Set RETENTION_VACUUM=true to reclaim freed space promptly with a VACUUM after a prune.", terms: "disk space storage size vacuum reclaim database grow full postgres bloat row counts" },
  { section: "capacity", title: "Server disk health", body: "For Docker deployments, GET /v1/config/storage and the dashboard Storage panel report the filesystem health of the disks data lives on — total, free and used per mount — plus a per-service breakdown of what's consuming the disk (the document store and a disk-backed model file). Point DISK_HEALTH_PATHS at the volume mounts to watch; the engine only sees filesystems mounted into its own container. Exported as verdict_disk_total_bytes, verdict_disk_free_bytes, verdict_disk_used_ratio and verdict_disk_component_bytes.", terms: "server disk health filesystem free space full volume docker mount df used percent breakdown per service consumed capacity node exporter cadvisor threshold alert running out of space" },
  { section: "capacity", title: "Scaling and Redis", body: "Set REDIS_URL and run several engine replicas behind a load balancer — idempotency, velocity and rate limits are shared in Redis, so a retry or a burst is enforced consistently across nodes. Postgres and the dashboard scale out either way.", terms: "scale scaling horizontal replicas redis load balancer high availability multi node cluster" },
  { section: "governance", title: "Right to erasure (GDPR)", body: "An admin can remove a user across the entity graph, the anomaly baseline, replay samples and the activity log with one call to POST /v1/privacy/erase. The append-only verdict log is out of scope by design — it holds only an event id, verdict and tags — and is aged out by retention.", terms: "gdpr privacy erasure erase delete user right to be forgotten personal data compliance ccpa remove data" },
  { section: "deploy", title: "Deployment and environment", body: "The engine refuses to start until AUTH_SECRET is a real secret and DATABASE_URL is set, so a bad deploy fails loudly. Keep the engine port private behind a TLS proxy. Health is at GET /health; metrics at GET /metrics in Prometheus format.", terms: "deploy production environment variables env config auth secret database url tls proxy health metrics prometheus" },
  { section: "security", title: "Auth, API keys and rotation", body: "Service API keys are random, SHA-256-hashed at rest, shown once, scoped and revocable. Operator auth uses scrypt-hashed passwords and signed bearer tokens with logout, logout-all and refresh. AUTH_SECRET rotates with zero forced logouts via AUTH_SECRET_PREVIOUS.", terms: "security auth authentication api key scope revoke rotate token bearer password login logout session jwt" },
  { section: "mcp", title: "LLM and MCP integration", body: "Verdict ships an official Model Context Protocol server so any LLM client — Claude Code, Claude Desktop, Cursor — can drive the engine as tools: decide, recent_decisions, analytics_summary, lookup_entity, backtest_policy. Point your coding agent at /llms.txt for a self-contained integration brief.", terms: "llm ai mcp model context protocol claude cursor agent tools llms.txt copilot assistant" },
];

/**
 * Query-expansion synonyms: when a query token matches a key (or any of its values), the whole group
 * is added to the search terms. This is what lets a query in plain language reach doc vocabulary —
 * "location" finds the geolocation passage, "how fast" finds throughput, "who changed" finds audit.
 */
export const SYNONYMS: string[][] = [
  ["fraud", "risk", "abuse", "fraudulent", "scam"],
  ["ring", "rings", "cluster", "network", "collusion", "graph", "farming"],
  ["location", "geo", "geolocation", "geoip", "country", "ip", "travel", "distance", "where"],
  ["impossible", "travel", "teleport", "jet", "distance", "velocity"],
  ["device", "fingerprint", "fingerprinting", "spoof", "spoofing", "clone", "cloning", "emulator", "bot"],
  ["fast", "speed", "performance", "throughput", "latency", "slow", "benchmark", "rps", "p99"],
  ["throttle", "throttling", "ratelimit", "rate", "limit", "budget", "429", "storm"],
  ["login", "signin", "authentication", "takeover", "credential", "stuffing", "account"],
  ["money", "amount", "payout", "withdrawal", "transaction", "currency", "payment", "charge"],
  ["model", "ml", "scorer", "logistic", "weights", "prediction", "ai", "learning"],
  ["cloud", "remote", "bucket", "s3", "registry", "url", "hotswap", "swap"],
  ["disk", "storage", "space", "size", "vacuum", "reclaim", "bloat", "filesystem", "volume", "free", "full", "mount", "df", "breakdown", "consumed"],
  ["retention", "prune", "delete", "old", "expire", "cleanup", "age"],
  ["audit", "who", "changed", "history", "accountability", "log"],
  ["webhook", "callback", "push", "subscribe", "event", "signature", "hmac"],
  ["notification", "notifications", "alert", "alerts", "slack", "telegram", "notify", "ping"],
  ["scale", "scaling", "replicas", "redis", "horizontal", "cluster", "loadbalancer", "multinode"],
  ["gdpr", "privacy", "erasure", "erase", "forgotten", "delete", "personal", "ccpa"],
  ["deploy", "deployment", "production", "docker", "compose", "env", "environment", "secret"],
  ["auth", "authentication", "key", "token", "password", "rotate", "revoke", "scope", "jwt"],
  ["llm", "ai", "mcp", "claude", "cursor", "agent", "assistant", "copilot"],
  ["batch", "bulk", "many", "async", "asynchronous", "background", "queue"],
  ["idempotency", "idempotent", "duplicate", "retry", "replay", "exactlyonce"],
  ["anomaly", "outlier", "unusual", "abnormal", "zscore", "deviation"],
  ["velocity", "frequency", "burst", "bursts", "attempts"],
  ["backtest", "simulate", "replay", "test", "whatif", "shadow", "precision", "recall"],
  ["rules", "rule", "dsl", "condition", "policy", "bands"],
  ["case", "cases", "review", "queue", "analyst", "manual", "investigate"],
  ["sdk", "client", "library", "typescript", "javascript", "node", "dart", "flutter", "python", "reactnative", "package", "wrapper"],
];
